# Generated by Django 3.2.6 on 2021-10-06 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeepJeep',
            fields=[
                ('beepId', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=200, null=True)),
                ('capacity', models.CharField(max_length=200, null=True)),
                ('beepStatus', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('routeId', models.AutoField(primary_key=True, serialize=False)),
                ('route_from', models.CharField(max_length=200, null=True)),
                ('route_to', models.CharField(max_length=200, null=True)),
                ('fare', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketId', models.AutoField(primary_key=True, serialize=False)),
                ('modeOfPayment', models.CharField(max_length=200, null=True)),
                ('validTime', models.DateField(auto_now_add=True)),
                ('beepId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beep.beepjeep')),
                ('routeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beep.route')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beep.user')),
            ],
        ),
    ]
