# Generated by Django 3.2.6 on 2021-10-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beep', '0002_alter_beepjeep_beepstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='beepId',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='routeId',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='userId',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='validTime',
            field=models.IntegerField(),
        ),
    ]
